CREATE DATABASE bd_dicio;
USE bd_dicio;

CREATE TABLE `tb_termos` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `nome` varchar(50) NOT NULL,
  `desc` text NOT NULL,
  `status` tinyint(4) DEFAULT 1,
  PRIMARY KEY (`id`)
);

INSERT INTO `tb_termos` (`nome`, `desc`, `status`, `id_user`) VALUES
	('Algorithm', 'uma série de instruções ou passos de procedimentos para a solução de um problema específico', 1),
    ('Caption', 'legenda, título, cabeçalho', 1),
    ('Alt Key', 'tecla Alt (tecla especial em um teclado de PC usada para ativar funções especiais', 1),
    ('Flowchart', 'gráfico, diagrama que mostra informação como uma série de linhas ou blocos.', 1),
    ('Amplifier', 'amplificador', 1),
    ('Close file', 'fechar um arquivo', 1),
    ('Analog / digital converter', 'conversor analógico / digital', 1),
    ('Data control', 'controle de dados, gereciamento de dados', 1),
    ('Auto activate', 'ativar automaticamente', 1),
    ('Backup(no MS – DOS)', 'comando para salvar os dados de um disco rígido em disquetes', 1),
    ('BOS (Basic Operating System)', 'Sistema Operacional Básico', 1),
    ('Bottom', 'fundo de alguma coisa inferior', 2),
    ('Bug', 'erro, falha em programa de computador', 2),
    ('Byte', 'byte, grupo de bits ou dígitos binários (geralmente oito que o computador opera como uma unidade simples)', 2),
    ('Caps Lock', '(trava das maiúsculas) tecla que permite que todos os caracteres sejam digitados em maiúsculas', 2),
    ('Compiler', 'compilar, converter um programa de linguagem de alto nível em um programa em código de máquina que pode ser executado diretamente', 2),
    ('Data Field', 'campo de dados, parte de uma situação, instrução de computador que contém a posição do dado', 2),
    ('DOS (Disk Operating System)', 'Sistema Operacional em disco', 2),
    ('Directory', 'diretório ou lista; método de organização de arquivos armazenados em disco', 2),
    ('Display', 'exibir, mostrar informação', 2),
    ('Extract file', 'extrair arquivo', 2),
    ('Edge', 'borda / margem', 2),
    ('Failure', 'falha, avaria, pane; qualquer problema grave causado por defeito no hardware ou software', 3),
    ('File set', 'conjunto de arquivos', 3),
    ('Flowchart', 'fluxograma', 3),
    ('Hardware', 'unidades físicas, componentes, circuitos integrados e discos e mecanismos que compõem um computador ou seus periféricos', 3),
    ('Hide Edges', 'esconder, ocultar bordas', 3),
    ('Integer', 'número inteiro (sem componentes fracionários)', 3),
    ('ink', 'tinta de caneta, de impressora', 3),
    ('USB', 'circuito paralelo universal em série, é um tipo de conexão para ligar e usar (Plug and Play) que permite a conexão de periféricos sem a necessidade de desligar o computador', 3),
    ('Tab', 'tabular, organizar textos em colunas', 3),
    ('Screen', 'proteger alguma coisa com uma tela', 3),
    ('Scroll', 'rolar a tela', 3),
    ('Server', 'servidor', 4),
    ('Set up', 'preparar equipamento para operação', 4),
    ('Shift', 'muda, deslocar, mudança', 4),
    ('Short cut', 'atalho', 4),
    ('Ram (Randon Access Memory)', 'Memória de acesso aleatório', 4),
    ('Reset', 'restaurar, inicializar', 4),
    ('Ruler', 'régua', 4),
    ('ROM (Read Only Memory)', 'Memória somente para leitura', 4),
    ('Password', 'senha', 4),
    ('Lock', 'travar / bloquear', 4),
    ('Load', 'carregar', 4)